version: "3"

services:
  postgres:
    image: mangeot/postgres4jibiki
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  ipolex:
    image: mangeot/ipolex
    volumes:
      - ipolex:/var/www/html/Dicos
    restart: always
    ports:
      - ${IPOLEX_PORT}:80

  jibiki:
    image: mangeot/jibiki
    environment:
      - SITE_NAME=${SITE_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - VALIDATOR_PASSWORD=${VALIDATOR_PASSWORD}
      - SPECIALIST_PASSWORD=${SPECIALIST_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ipolex:/ipolex
      - ./Cesselin_fra-jpn:/Cesselin_fra-jpn
    restart: always
    ports:
      - ${JIBIKI_PORT}:8999
    depends_on:
      postgres:
        condition: service_healthy

  jibikirest:
    image: mangeot/jibikirest
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    restart: always
    ports:
      - ${API_PORT}:80
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  ipolex:
  postgresql:
