#!/bin/sh

#
# Minimal startup script
#

set -e
cd "`dirname $0`"

#Default values
MULTISERVER_CONF="./conf/multiserver.conf"
EXEC=nohup

while [ $# -gt 0 ]; do
  case "$1" in 
   --debug ) MULTISERVER_CONF="./conf/monoserver.conf" ; shift 1 ;;
   --exec ) EXEC=exec ; shift 1 ;;
   --help | -h ) echo "Usage: $0 [--help] [--debug] [--exec]"
   				 echo "  --help : display this help message and exits."; 
   				 echo "  --debug : Run the server directly as HTTP on port 8999."; 
   				 echo "  --exec : use exec instead of nohup to run the server."; 
				 exit ;;
   * ) echo "Unrecognized option $arg, use $0 --help for details." ; exit ;;
  esac
done

JAVA="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java"
ENHYDRA_LIB="/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/enhydra.jar"

# Check for java
if [ ! -x $JAVA ] ; then
    echo "Error: Cannot find Java VM."
    exit 1
fi

# Check for the Enhydra classes
if [ ! -r $ENHYDRA_LIB ] ; then
    echo "Error: Cannot find Enhydra classes."
    exit 1
fi

#
# Build up classpath.
#
CLASSPATH=/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/admin.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/bcel.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/core.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/debugger.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/enhydra.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/gnu-regexp.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/jtidy.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/log4j.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/servlet.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/tomcat.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/util.jar
#CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/xercesImpl.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/xhtml.jar
#CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/xml-apis.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/xmlc.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/dods/lib/dbmanager-api.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/dods/lib/dbmanager.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/dods/lib/stdcaches.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/dods/lib/stdconnection.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/dods/lib/stdtransaction.jar
#CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/dom/xmlc-chtml.jar
#CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/dom/xmlc-voicexml.jar
#CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/dom/xmlc-wml.jar
CLASSPATH=$CLASSPATH:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/lib/xhtml.jar

#CLASSPATH=$(/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/bin/setclass)${PS}$(/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1/bin/setdomclass)
export CLASSPATH

#APPCP=@ANT_LIB@
APPCP=/Users/yingzhang/Projet/Jibiki/toolsforjibiki/xalan-j_2_7_0/xalan.jar
APPCP=$APPCP:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/xalan-j_2_7_0/xercesImpl.jar
APPCP=$APPCP:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/xalan-j_2_7_0/xml-apis.jar
APPCP=$APPCP:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/xalan-j_2_7_0/xsltc.jar
APPCP=$APPCP:/usr/share/java/postgresql-9.1-901.jdbc4.jar
#APPCP=$APPCP:${papillon.saxon8.jar}
APPCP=$APPCP:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/fop-0.20.5/build/fop.jar
APPCP=$APPCP:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/fop-0.20.5/lib/avalon-framework-cvs-20020806.jar
APPCP=$APPCP:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/fop-0.20.5/lib/batik.jar
APPCP=$APPCP:/Users/yingzhang/Projet/Jibiki/toolsforjibiki/javamail-1.4/mail.jar
APPCP=$APPCP:${ENHYDRA_LIB}:${CLASSPATH}

echo APPCP = $APPCP

$EXEC ${JAVA} \
	-cp "${APPCP}" \
	-Dfile.encoding=UTF8 \
	-Denhydra.home=/Users/yingzhang/Projet/Jibiki/toolsforjibiki/enhydra5.1 \
	com.lutris.multiServer.MultiServer \
	"${MULTISERVER_CONF}"

