/* Generated By:JavaCC: Do not edit this line. UNLParserConstants.java */
package fr.imag.clips.papillon.business.pivax.unl_graph;

public interface UNLParserConstants {

  int EOF = 0;
  int ALPHA = 1;
  int NUM = 2;
  int ALPHANUM = 3;
  int WHITESPACES = 4;
  int HEADWORD_CHARACTERS = 5;
  int COMMENT = 10;
  int PARO = 11;
  int PARF = 12;
  int CHEVRD = 13;
  int CHEVRG = 14;
  int COMMA = 15;
  int DEUXPOINT = 16;
  int POURCENT = 17;
  int DOC = 18;
  int PARAGRAPH = 19;
  int TITLE = 20;
  int SENTENCE = 21;
  int NODELIST = 22;
  int END_DOC = 23;
  int END_PARAGRAPH = 24;
  int END_TITLE = 25;
  int END_SENTENCE = 26;
  int END_NODELIST = 27;
  int COLON_NUMBER = 35;
  int DBLQUOTED = 36;
  int GENERIC_TOKEN = 37;
  int ATTR = 38;

  int DEFAULT = 0;
  int WithinNLText = 1;

  String[] tokenImage = {
    "<EOF>",
    "<ALPHA>",
    "<NUM>",
    "<ALPHANUM>",
    "<WHITESPACES>",
    "<HEADWORD_CHARACTERS>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\"<\"",
    "\",\"",
    "\":\"",
    "\"%\"",
    "<DOC>",
    "<PARAGRAPH>",
    "<TITLE>",
    "<SENTENCE>",
    "<NODELIST>",
    "<END_DOC>",
    "<END_PARAGRAPH>",
    "<END_TITLE>",
    "<END_SENTENCE>",
    "<END_NODELIST>",
    "<token of kind 28>",
    "<token of kind 29>",
    "\"{/org}\"",
    "<token of kind 31>",
    "<token of kind 32>",
    "\"{unl}\"",
    "\"{/unl}\"",
    "<COLON_NUMBER>",
    "<DBLQUOTED>",
    "<GENERIC_TOKEN>",
    "<ATTR>",
  };

}
