#!/bin/sh

sed -i "s#\%TOOLSFORJIBIKI_DIR\%#/toolsforjibiki#g" /jibiki/papillon.properties

sed -i "s#\%ADMIN_PASSWORD\%#$ADMIN_PASSWORD#g" /jibiki/papillon.properties

sed -i "s#\%SPECIALIST_PASSWORD\%#$SPECIALIST_PASSWORD#g" /jibiki/papillon.properties

sed -i "s#\%VALIDATOR_PASSWORD\%#$VALIDATOR_PASSWORD#g" /jibiki/papillon.properties

sed -i "s#\%DATABASE_HOST\%#$DATABASE_HOST#g" /jibiki/papillon.properties

sed -i "s#\%DATABASE_NAME\%#$DATABASE_NAME#g" /jibiki/papillon.properties

sed -i "s#\%DATABASE_USER\%#$DATABASE_USER#g" /jibiki/papillon.properties

sed -i "s#\%DATABASE_PASSWORD\%#$DATABASE_PASSWORD#g" /jibiki/papillon.properties

sed -i "s/Papillon.Users.Groups.Password.admin *=.*$/Papillon.Users.Groups.Password.admin = \"$ADMIN_PASSWORD\"/g" /jibiki/output/conf/Papillon.conf
sed -i "s/Papillon.Users.Groups.Password.specialist *=.*$/Papillon.Users.Groups.Password.specialist = \"$SPECIALIST_PASSWORD\"/g" /jibiki/output/conf/Papillon.conf
sed -i "s/Papillon.Users.Groups.Password.validator *=.*$/Papillon.Users.Groups.Password.validator = \"$VALIDATOR_PASSWORD\"/g" /jibiki/output/conf/Papillon.conf
sed -i "s/papillondb.server.url *=.*$/papillondb.server.url=jdbc:postgresql:\/\/$DATABASE_HOST\/$DATABASE_NAME/g" /jibiki/output/conf/Papillon.conf
sed -i "s/DatabaseManager.DB.papillon.Connection.Url *=.*$/DatabaseManager.DB.papillon.Connection.Url=jdbc:postgresql:\/\/$DATABASE_HOST\/$DATABASE_NAME/g" /jibiki/output/conf/Papillon.conf
sed -i "s/papillondb.user *=.*$/papillondb.user=$DATABASE_USER/g" /jibiki/output/conf/Papillon.conf
sed -i "s/DatabaseManager.DB.papillon.Connection.User *=.*$/DatabaseManager.DB.papillon.Connection.User=$DATABASE_USER/g" /jibiki/output/conf/Papillon.conf
sed -i "s/papillondb.password *=.*$/papillondb.password=$DATABASE_PASSWORD/g" /jibiki/output/conf/Papillon.conf
sed -i "s/DatabaseManager.DB.papillon.Connection.Password *=.*$/DatabaseManager.DB.papillon.Connection.Password=$DATABASE_PASSWORD/g" /jibiki/output/conf/Papillon.conf


echo "Server started with ADMIN_PASSWORD=$ADMIN_PASSWORD \
	SPECIALIST_PASSWORD=$SPECIALIST_PASSWORD \
	VALIDATOR_PASSWORD=$VALIDATOR_PASSWORD \
	DATABASE_HOST=$DATABASE_HOST \
	DATABASE_NAME=$DATABASE_NAME \
	DATABASE_USER=$DATABASE_USER \
	DATABASE_PASSWORD=$DATABASE_PASSWORD"
